Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

schema = graphviz.Digraph(filename, filename=filename+'.gv')
schema.graph_attr['rankdir'] = 'LR'
# graphviz
schema.attr('node', shape=symbol["iri"])
schema.node('fileURI')
schema.attr('node', shape=symbol["class"])
schema.node('dcatdataset', label='dcat:dataset')
schema.node('Q63082925', label='wd:Q63082925')
schema.attr('node', shape=symbol["literal"])
schema.node('Office Open XML Spreadsheet Document@en')
schema.attr('node', shape='octagon')
schema.node('filename', label='xsd:string')
schema.node('filedatecreated', label='xsd:date')
schema.node('filedatemodified', label='xsd:date')
schema.edge('fileURI', 'dcatdataset', label='rdf:type')
schema.edge('fileURI', 'Q63082925', label='dcterms:format')
schema.edge('Q63082925', 'Office Open XML Spreadsheet Document@en', label='rdfs:label')
schema.edge('fileURI', 'filename', label="rdfs:label")
schema.edge('fileURI', 'filedatecreated', label="dcterms:issued")
schema.edge('fileURI', 'filedatemodified', label="dcterms:modified")

# ShEx
dataexpressions = []
dataexpressions.append(TripleConstraint(predicate=IRIREF(RDF.type),valueExpr=NodeConstraint(values=[DCAT.Dataset])))
dataexpressions.append(TripleConstraint(predicate=IRIREF(DCTERMS.format),valueExpr=NodeConstraint(values=[IRIREF(WD.Q63082925)]), annotations=[Annotation(RDFS.label,ObjectLiteral("Office Open XML Spreadsheet Document", language="en"))]))
dataexpressions.append(TripleConstraint(predicate=IRIREF(RDFS.label), valueExpr=NodeConstraint(datatype=XSD.string)))
dataexpressions.append(TripleConstraint(predicate=IRIREF(DCTERMS.issued), valueExpr=NodeConstraint(datatype=XSD.dateTime)))
dataexpressions.append(TripleConstraint(predicate=IRIREF(DCTERMS.modified), valueExpr=NodeConstraint(datatype=XSD.dateTime)))

# RDF
rdf = Graph()
rdf.add((fileURI, RDF.type, DCAT.Dataset))
rdf.add((fileURI, DCTERMS.format, WD.Q63082925))
rdf.add((WD.Q63082925, RDFS.label, Literal("Office Open XML Spreadsheet Document", lang="en")))
rdf.add((fileURI, RDFS.label, Literal(filename, datatype=XSD.string)))
datecreated = os.path.getctime(filename)
rdf.add((fileURI, DCTERMS.issued, Literal(datetime.fromtimestamp(datecreated).strftime('%Y-%m-%dT%H:%M:%SZ'), datatype=XSD.dateTime)))
datemodified = os.path.getmtime(filename)
rdf.add((fileURI, DCTERMS.modified, Literal(datetime.fromtimestamp(datemodified).strftime('%Y-%m-%dT%H:%M:%SZ'), datatype=XSD.dateTime)))

gbm1 = Schema()
shapesns = 'http://a.example/shapes'
startshape = shapesns + "#primarydata"
gbm1.shapes = [Shape(startshape, expression=EachOf(expressions=dataexpressions))]
gbm1.start = startshape

# print(str(ShExC(gbm1, base=shapesns, namespaces=rdf.namespace_manager)))
schema
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 36[0m
[1;32m     34[0m rdf[38;5;241m.[39madd((WD[38;5;241m.[39mQ63082925, RDFS[38;5;241m.[39mlabel, Literal([38;5;124m"[39m[38;5;124mOffice Open XML Spreadsheet Document[39m[38;5;124m"[39m, lang[38;5;241m=[39m[38;5;124m"[39m[38;5;124men[39m[38;5;124m"[39m)))
[1;32m     35[0m rdf[38;5;241m.[39madd((fileURI, RDFS[38;5;241m.[39mlabel, Literal(filename, datatype[38;5;241m=[39mXSD[38;5;241m.[39mstring)))
[0;32m---> 36[0m datecreated [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43mpath[49m[38;5;241;43m.[39;49m[43mgetctime[49m[43m([49m[43mfilename[49m[43m)[49m
[1;32m     37[0m rdf[38;5;241m.[39madd((fileURI, DCTERMS[38;5;241m.[39missued, Literal(datetime[38;5;241m.[39mfromtimestamp(datecreated)[38;5;241m.[39mstrftime([38;5;124m'[39m[38;5;124m%[39m[38;5;124mY-[39m[38;5;124m%[39m[38;5;124mm-[39m[38;5;132;01m%d[39;00m[38;5;124mT[39m[38;5;124m%[39m[38;5;124mH:[39m[38;5;124m%[39m[38;5;124mM:[39m[38;5;124m%[39m[38;5;124mSZ[39m[38;5;124m'[39m), datatype[38;5;241m=[39mXSD[38;5;241m.[39mdateTime)))
[1;32m     38[0m datemodified [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mgetmtime(filename)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/genericpath.py:65[0m, in [0;36mgetctime[0;34m(filename)[0m
[1;32m     63[0m [38;5;28;01mdef[39;00m [38;5;21mgetctime[39m(filename):
[1;32m     64[0m [38;5;250m    [39m[38;5;124;03m"""Return the metadata change time of a file, reported by os.stat()."""[39;00m
[0;32m---> 65[0m     [38;5;28;01mreturn[39;00m [43mos[49m[38;5;241;43m.[39;49m[43mstat[49m[43m([49m[43mfilename[49m[43m)[49m[38;5;241m.[39mst_ctime

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../creating-rdf/data/Sample clinical data_July 2022.xlsx'

